name: Jekyll GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # GitHub Pages 兼容的 Ruby 版本
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --trace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
